// 声明式流水线
pipeline {
    agent any
    stages {
        stage('check') {
            agent {
                docker {
                    image 'maven:3-alpine'
                    args '-v /root/.m2:/root/.m2'
                }
            }
            steps {
                //我这里配置在jenkins上了  git 'https://github.com/originalblackhole/jenkins-test.git'
                git "https://gitee.com/original-blackhole/jenkins-test.git"
                sh 'mvn -B -DskipTests clean package'
            }
        }

        stage('build'){
            agent {
                dockerfile {
                    filename 'Dockerfile'
                }
            }
            steps {
                sh " ./build.sh"
            }
        }

        stage('deploy'){
            steps {
                sh ' ./docker.sh'
            }
        }
    }
    post {
        always {
            //junit '**/target/*.xml'
        }
        failure {
            //mail to: team@example.com, subject: 'The Pipeline failed :('
        }
    }
}